name: final_project
description: "WeatherNow App by Group6"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- THÊM VÀO ĐÂY (thụt lề đúng 2 space) ---
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # HTTP & API
  dio: ^5.4.3
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.3

  # UI & Charts
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Maps
  maps_launcher: ^3.0.0+1

  # Animations
  lottie: ^3.1.2

  # Date & Time
  intl: ^0.19.0

  # Notifications
  flutter_local_notifications: ^17.1.2

  # Images
  cached_network_image: ^3.3.1

  # Utils
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  path_provider: ^2.1.3

  # Widgets
  home_widget: ^0.6.0

  # CSV Export
  csv: ^6.0.0
  pdf: ^3.10.8
  collection: ^1.18.0

  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/weather_icons/
    - assets/images/illustrations/
    - assets/lottie/
    - assets/data/
